// Auto-generated mock activities data
const activities = [
  {
    "id": 1,
    "title": "Ganesh Idol Installation",
    "description": "Installation of Lord Ganesha idol with Vedic rituals and chanting by priests. The ceremony will begin with Ganapati Atharvashirsha followed by Pran Pratishtha.",
    "date": "2026-12-28",
    "time": "14:30 AM",
    "venue": "Wagholi Bahuchar Mata Mandir",
    "organizer": "Sports Committee",
    "budget": 56761,
    "status": "Upcoming",
    "bannerImage": null,
    "category": "Religious"
  },
  {
    "id": 2,
    "title": "Morning Aarti",
    "description": "Daily morning aarti with traditional devotional songs and offerings. Devotees gather to seek blessings of Lord Ganesha.",
    "date": "2026-10-22",
    "time": "18:00 AM",
    "venue": "Hadapsar Gadital",
    "organizer": "Social Service Cell",
    "budget": 32650,
    "status": "Upcoming",
    "bannerImage": null,
    "category": "Religious"
  },
  {
    "id": 3,
    "title": "Evening Aarti",
    "description": "Evening aarti with grand lamp lighting and bhajans. Special lighting arrangement for the evening ceremony.",
    "date": "2026-07-28",
    "time": "11:30 PM",
    "venue": "Deccan Gymkhana Ground",
    "organizer": "Education Committee",
    "budget": 138401,
    "status": "Upcoming",
    "bannerImage": null,
    "category": "Religious"
  },
  {
    "id": 4,
    "title": "Bhajan Sandhya",
    "description": "Spiritual evening filled with devotional bhajans and kirtans performed by local artists.",
    "date": "2026-07-02",
    "time": "15:30 PM",
    "venue": "Kothrud Gadge Maharaj Hall",
    "organizer": "Environment Cell",
    "budget": 155666,
    "status": "Upcoming",
    "bannerImage": null,
    "category": "Cultural"
  },
  {
    "id": 5,
    "title": "Mahaprasad",
    "description": "Community feast organized for all devotees and members. Traditional Maharashtra cuisine including puran poli, modak and other delicacies.",
    "date": "2026-12-12",
    "time": "17:00 AM",
    "venue": "Mandal Headquarters",
    "organizer": "Cultural Committee",
    "budget": 26638,
    "status": "Upcoming",
    "bannerImage": null,
    "category": "Religious"
  },
  {
    "id": 6,
    "title": "Blood Donation Camp",
    "description": "Annual blood donation drive in collaboration with Red Cross. Free health checkup for donors.",
    "date": "2026-09-29",
    "time": "21:30 PM",
    "venue": "Shivaji Mandir Hall",
    "organizer": "Shiv Mandal Committee",
    "budget": 180682,
    "status": "Ongoing",
    "bannerImage": null,
    "category": "Social"
  },
  {
    "id": 7,
    "title": "Medical Camp",
    "description": "Free medical checkup camp with general physicians, eye specialists and dentists. Free medicines distributed.",
    "date": "2026-09-25",
    "time": "15:00 PM",
    "venue": "Baner Sports Complex",
    "organizer": "Women's Wing",
    "budget": 33994,
    "status": "Ongoing",
    "bannerImage": null,
    "category": "Health"
  },
  {
    "id": 8,
    "title": "Tree Plantation",
    "description": "Plantation of 500 trees in and around the mandal area. Each member is encouraged to plant and adopt a tree.",
    "date": "2026-10-13",
    "time": "19:30 AM",
    "venue": "Viman Nagar Township Ground",
    "organizer": "Environment Cell",
    "budget": 86195,
    "status": "Ongoing",
    "bannerImage": null,
    "category": "Environment"
  },
  {
    "id": 9,
    "title": "Cultural Programs",
    "description": "Grand cultural evening featuring classical and folk dances, dramas and musical performances by renowned artists.",
    "date": "2026-11-05",
    "time": "14:00 AM",
    "venue": "Laxmi Road Community Center",
    "organizer": "Health Committee",
    "budget": 88484,
    "status": "Ongoing",
    "bannerImage": null,
    "category": "Cultural"
  },
  {
    "id": 10,
    "title": "Sports Events",
    "description": "Inter-colony cricket, kabaddi and volleyball tournaments for youth. Trophies and medals for winners.",
    "date": "2026-10-12",
    "time": "14:00 PM",
    "venue": "Mandal Headquarters",
    "organizer": "Managing Committee",
    "budget": 34617,
    "status": "Ongoing",
    "bannerImage": null,
    "category": "Sports"
  },
  {
    "id": 11,
    "title": "Women's Programs",
    "description": "Special programs for women including mehendi competition, cooking competition and health awareness sessions.",
    "date": "2026-10-30",
    "time": "12:30 AM",
    "venue": "Pimple Saudagar Club House",
    "organizer": "Women's Wing",
    "budget": 88991,
    "status": "Ongoing",
    "bannerImage": null,
    "category": "Social"
  },
  {
    "id": 12,
    "title": "Children's Competitions",
    "description": "Drawing, essay writing, rangoli, and fancy dress competitions for children. Prizes for all participants.",
    "date": "2026-07-25",
    "time": "11:30 PM",
    "venue": "Shivaji Mandir Hall",
    "organizer": "Women's Wing",
    "budget": 143783,
    "status": "Ongoing",
    "bannerImage": null,
    "category": "Cultural"
  },
  {
    "id": 13,
    "title": "Visarjan Procession",
    "description": "Grand Ganesh Visarjan procession through the city with dhol-tasha, dance groups and devotional chanting.",
    "date": "2026-07-13",
    "time": "19:30 AM",
    "venue": "Baner Sports Complex",
    "organizer": "Social Service Cell",
    "budget": 187238,
    "status": "Completed",
    "bannerImage": null,
    "category": "Religious"
  },
  {
    "id": 14,
    "title": "Health Checkup Camp",
    "description": "Comprehensive health screening camp including blood sugar, blood pressure, cholesterol tests and BMI check.",
    "date": "2026-09-23",
    "time": "20:00 PM",
    "venue": "Viman Nagar Township Ground",
    "organizer": "Cultural Committee",
    "budget": 177768,
    "status": "Completed",
    "bannerImage": null,
    "category": "Health"
  },
  {
    "id": 15,
    "title": "Educational Support",
    "description": "Distribution of school supplies, books and uniforms to underprivileged children from nearby communities.",
    "date": "2026-08-31",
    "time": "10:30 AM",
    "venue": "Pimple Saudagar Club House",
    "organizer": "Environment Cell",
    "budget": 141333,
    "status": "Completed",
    "bannerImage": null,
    "category": "Education"
  },
  {
    "id": 16,
    "title": "Scholarship Distribution",
    "description": "Merit-based scholarships for students from economically weaker sections. Support for higher education.",
    "date": "2026-11-06",
    "time": "15:30 PM",
    "venue": "Viman Nagar Township Ground",
    "organizer": "Cultural Committee",
    "budget": 24182,
    "status": "Completed",
    "bannerImage": null,
    "category": "Education"
  },
  {
    "id": 17,
    "title": "Charity Programs",
    "description": "Distribution of food grains, clothes and essentials to orphanages and old age homes in the city.",
    "date": "2026-12-03",
    "time": "08:00 PM",
    "venue": "Deccan Gymkhana Ground",
    "organizer": "Education Committee",
    "budget": 77927,
    "status": "Completed",
    "bannerImage": null,
    "category": "Social"
  },
  {
    "id": 18,
    "title": "Food Distribution",
    "description": "Daily meal distribution for underprivileged during the festival season. Serving over 1000 people daily.",
    "date": "2026-09-14",
    "time": "19:30 AM",
    "venue": "Wagholi Bahuchar Mata Mandir",
    "organizer": "Sports Committee",
    "budget": 177350,
    "status": "Completed",
    "bannerImage": null,
    "category": "Social"
  },
  {
    "id": 19,
    "title": "Environmental Awareness",
    "description": "Workshop on eco-friendly Ganesh idols, waste management and plastic-free festival celebration.",
    "date": "2026-10-27",
    "time": "17:30 PM",
    "venue": "Pimple Saudagar Club House",
    "organizer": "Education Committee",
    "budget": 153614,
    "status": "Completed",
    "bannerImage": null,
    "category": "Environment"
  },
  {
    "id": 20,
    "title": "Youth Development Program",
    "description": "Skill development workshops, leadership training and career guidance sessions for local youth.",
    "date": "2026-12-16",
    "time": "21:30 PM",
    "venue": "Deccan Gymkhana Ground",
    "organizer": "Environment Cell",
    "budget": 150052,
    "status": "Completed",
    "bannerImage": null,
    "category": "Education"
  }
];

export default activities;
