// Mock attendance records for Ganesh Mandal volunteers
const attendance = [
  {
    id: "ATT-0001",
    volunteerId: "VOL-0001",
    volunteerName: "Rajesh Sharma",
    volunteerMobile: "9823145678",
    volunteerRole: "President",
    eventId: "EVT-0001",
    eventName: "Murti Sthapana",
    attendanceDate: "2026-08-26",
    status: "Present",
    remarks: "Supervised entire ceremony"
  },
  {
    id: "ATT-0002",
    volunteerId: "VOL-0002",
    volunteerName: "Suresh Patil",
    volunteerMobile: "9822567890",
    volunteerRole: "Vice President",
    eventId: "EVT-0001",
    eventName: "Murti Sthapana",
    attendanceDate: "2026-08-26",
    status: "Present",
    remarks: "Managed guest arrangements"
  },
  {
    id: "ATT-0003",
    volunteerId: "VOL-0007",
    volunteerName: "Sanjay More",
    volunteerMobile: "9823901234",
    volunteerRole: "Decoration Head",
    eventId: "EVT-0001",
    eventName: "Murti Sthapana",
    attendanceDate: "2026-08-26",
    status: "Present",
    remarks: "Led decoration setup from morning"
  },
  {
    id: "ATT-0004",
    volunteerId: "VOL-0015",
    volunteerName: "Datta Patil",
    volunteerMobile: "9823789012",
    volunteerRole: "Security Head",
    eventId: "EVT-0001",
    eventName: "Murti Sthapana",
    attendanceDate: "2026-08-26",
    status: "Present",
    remarks: "Coordinated security team of 8 members"
  },
  {
    id: "ATT-0005",
    volunteerId: "VOL-0017",
    volunteerName: "Ashok Shinde",
    volunteerMobile: "9890234567",
    volunteerRole: "Sound System Coordinator",
    eventId: "EVT-0001",
    eventName: "Murti Sthapana",
    attendanceDate: "2026-08-26",
    status: "Present",
    remarks: "Sound system installed by 5 AM"
  },
  {
    id: "ATT-0006",
    volunteerId: "VOL-0005",
    volunteerName: "Nikhil Kulkarni",
    volunteerMobile: "9821789012",
    volunteerRole: "Event Organizer",
    eventId: "EVT-0004",
    eventName: "Dholshek Path",
    attendanceDate: "2026-08-27",
    status: "Present",
    remarks: "Organized the entire procession route"
  },
  {
    id: "ATT-0007",
    volunteerId: "VOL-0006",
    volunteerName: "Pooja Thakur",
    volunteerMobile: "9876543210",
    volunteerRole: "Event Coordinator",
    eventId: "EVT-0004",
    eventName: "Dholshek Path",
    attendanceDate: "2026-08-27",
    status: "Late",
    remarks: "Arrived 30 minutes late due to traffic"
  },
  {
    id: "ATT-0008",
    volunteerId: "VOL-0016",
    volunteerName: "Pramod Gaikwad",
    volunteerMobile: "9821456790",
    volunteerRole: "Crowd Management",
    eventId: "EVT-0004",
    eventName: "Dholshek Path",
    attendanceDate: "2026-08-27",
    status: "Present",
    remarks: "Managed crowd at 3 junction points"
  },
  {
    id: "ATT-0009",
    volunteerId: "VOL-0009",
    volunteerName: "Rohan Mane",
    volunteerMobile: "9890678901",
    volunteerRole: "Social Media Manager",
    eventId: "EVT-0006",
    eventName: "Cultural Program - Day 3",
    attendanceDate: "2026-08-28",
    status: "Present",
    remarks: "Live streamed the entire cultural program"
  },
  {
    id: "ATT-0010",
    volunteerId: "VOL-0010",
    volunteerName: "Aditi Shinde",
    volunteerMobile: "9823567890",
    volunteerRole: "Photographer",
    eventId: "EVT-0006",
    eventName: "Cultural Program - Day 3",
    attendanceDate: "2026-08-28",
    status: "Present",
    remarks: "Captured over 500 photos throughout the event"
  },
  {
    id: "ATT-0011",
    volunteerId: "VOL-0013",
    volunteerName: "Vinayak Satpute",
    volunteerMobile: "9822678902",
    volunteerRole: "Prasad Coordinator",
    eventId: "EVT-0008",
    eventName: "Modak Competition",
    attendanceDate: "2026-08-29",
    status: "Present",
    remarks: "Managed modak competition setup and judging"
  },
  {
    id: "ATT-0012",
    volunteerId: "VOL-0014",
    volunteerName: "Priya Jagtap",
    volunteerMobile: "9890345679",
    volunteerRole: "Food Arrangement",
    eventId: "EVT-0008",
    eventName: "Modak Competition",
    attendanceDate: "2026-08-29",
    status: "Present",
    remarks: "Arranged ingredients for 30 participants"
  },
  {
    id: "ATT-0013",
    volunteerId: "VOL-0001",
    volunteerName: "Rajesh Sharma",
    volunteerMobile: "9823145678",
    volunteerRole: "President",
    eventId: "EVT-0009",
    eventName: "Sharad Khel",
    attendanceDate: "2026-08-30",
    status: "Present",
    remarks: "Inaugurated the sports tournament"
  },
  {
    id: "ATT-0014",
    volunteerId: "VOL-0003",
    volunteerName: "Amit Deshmukh",
    volunteerMobile: "9890123456",
    volunteerRole: "Secretary",
    eventId: "EVT-0010",
    eventName: "Seminars on Social Issues",
    attendanceDate: "2026-08-31",
    status: "Present",
    remarks: "Moderated the panel discussion"
  },
  {
    id: "ATT-0015",
    volunteerId: "VOL-0020",
    volunteerName: "Deepak Rao",
    volunteerMobile: "9823678902",
    volunteerRole: "Media Coordinator",
    eventId: "EVT-0010",
    eventName: "Seminars on Social Issues",
    attendanceDate: "2026-08-31",
    status: "Present",
    remarks: "Coordinated press coverage and media invites"
  },
  {
    id: "ATT-0016",
    volunteerId: "VOL-0006",
    volunteerName: "Pooja Thakur",
    volunteerMobile: "9876543210",
    volunteerRole: "Event Coordinator",
    eventId: "EVT-0011",
    eventName: "Women's Day Celebration",
    attendanceDate: "2026-09-01",
    status: "Present",
    remarks: "Coordinated all women volunteers"
  },
  {
    id: "ATT-0017",
    volunteerId: "VOL-0019",
    volunteerName: "Seema Kamble",
    volunteerMobile: "9876123457",
    volunteerRole: "VIP Guest Coordinator",
    eventId: "EVT-0011",
    eventName: "Women's Day Celebration",
    attendanceDate: "2026-09-01",
    status: "Present",
    remarks: "Hosted chief guest and felicitation ceremony"
  },
  {
    id: "ATT-0018",
    volunteerId: "VOL-0011",
    volunteerName: "Mangesh Gavhane",
    volunteerMobile: "9821890124",
    volunteerRole: "Cash Collection Volunteer",
    eventId: "EVT-0013",
    eventName: "Blood Donation Camp",
    attendanceDate: "2026-09-02",
    status: "Present",
    remarks: "Managed registration desk for blood donation"
  },
  {
    id: "ATT-0019",
    volunteerId: "VOL-0012",
    volunteerName: "Sneha Kulkarni",
    volunteerMobile: "9876432110",
    volunteerRole: "Sponsor Coordinator",
    eventId: "EVT-0013",
    eventName: "Blood Donation Camp",
    attendanceDate: "2026-09-02",
    status: "Absent",
    remarks: "On leave due to family emergency"
  },
  {
    id: "ATT-0020",
    volunteerId: "VOL-0013",
    volunteerName: "Vinayak Satpute",
    volunteerMobile: "9822678902",
    volunteerRole: "Prasad Coordinator",
    eventId: "EVT-0014",
    eventName: "Community Dinner",
    attendanceDate: "2026-09-03",
    status: "Present",
    remarks: "Oversaw kitchen operations for 500+ people"
  },
  {
    id: "ATT-0021",
    volunteerId: "VOL-0014",
    volunteerName: "Priya Jagtap",
    volunteerMobile: "9890345679",
    volunteerRole: "Food Arrangement",
    eventId: "EVT-0014",
    eventName: "Community Dinner",
    attendanceDate: "2026-09-03",
    status: "Present",
    remarks: "Managed food serving stations"
  },
  {
    id: "ATT-0022",
    volunteerId: "VOL-0018",
    volunteerName: "Manoj Deshmukh",
    volunteerMobile: "9822345679",
    volunteerRole: "Electrical Team",
    eventId: "EVT-0014",
    eventName: "Community Dinner",
    attendanceDate: "2026-09-03",
    status: "Present",
    remarks: "Set up lighting for open ground dinner"
  },
  {
    id: "ATT-0023",
    volunteerId: "VOL-0001",
    volunteerName: "Rajesh Sharma",
    volunteerMobile: "9823145678",
    volunteerRole: "President",
    eventId: "EVT-0015",
    eventName: "Prize Distribution",
    attendanceDate: "2026-09-05",
    status: "Present",
    remarks: "Presided over the prize distribution ceremony"
  },
  {
    id: "ATT-0024",
    volunteerId: "VOL-0004",
    volunteerName: "Prakash Jadhav",
    volunteerMobile: "9823456790",
    volunteerRole: "Treasurer",
    eventId: "EVT-0015",
    eventName: "Prize Distribution",
    attendanceDate: "2026-09-05",
    status: "Present",
    remarks: "Presented financial summary and trophy distribution"
  },
  {
    id: "ATT-0025",
    volunteerId: "VOL-0015",
    volunteerName: "Datta Patil",
    volunteerMobile: "9823789013",
    volunteerRole: "Security Head",
    eventId: "EVT-0007",
    eventName: "Ganesh Visarjan",
    attendanceDate: "2026-09-05",
    status: "Present",
    remarks: "Led security team for entire visarjan procession"
  }
];

export default attendance;
