const events = [
  {
    "id": 1,
    "eventName": "Ganesh Idol Installation Ceremony",
    "eventCategory": "Day 1",
    "festivalDay": "Day 1",
    "festivalYear": "2024",
    "date": "2024-09-07",
    "startTime": "06:00",
    "endTime": "10:00",
    "venue": "Mandal Ground, Pune",
    "description": "Traditional Ganesh idol installation with Vedic rituals and prayers.",
    "organizer": "Rajesh Deshmukh",
    "coordinator": "Priya Patil",
    "budget": 50000,
    "status": "Completed"
  },
  {
    "id": 2,
    "eventName": "Morning Aarti",
    "eventCategory": "Daily",
    "festivalDay": "Daily",
    "festivalYear": "2024",
    "date": "2024-09-08",
    "startTime": "07:00",
    "endTime": "08:00",
    "venue": "Mandal Ground, Pune",
    "description": "Daily morning aarti for Lord Ganesha.",
    "organizer": "Meera Kulkarni",
    "coordinator": "Anjali More",
    "budget": 5000,
    "status": "Completed"
  },
  {
    "id": 3,
    "eventName": "Cultural Program",
    "eventCategory": "Day 5",
    "festivalDay": "Day 5",
    "festivalYear": "2024",
    "date": "2024-09-11",
    "startTime": "18:00",
    "endTime": "22:00",
    "venue": "Community Hall, Pune",
    "description": "Cultural performances including dance, music, and drama.",
    "organizer": "Sneha Joshi",
    "coordinator": "Kavita Bhosale",
    "budget": 30000,
    "status": "Completed"
  },
  {
    "id": 4,
    "eventName": "Grand Visarjan",
    "eventCategory": "Final Day",
    "festivalDay": "Final Day",
    "festivalYear": "2024",
    "date": "2024-09-17",
    "startTime": "06:00",
    "endTime": "18:00",
    "venue": "Lakdi Pul to River",
    "description": "Grand Ganesh Visarjan procession with music and dance.",
    "organizer": "Vikram Singh",
    "coordinator": "Rajesh Deshmukh",
    "budget": 75000,
    "status": "Planned"
  },
  {
    "id": 5,
    "eventName": "Prasad Distribution",
    "eventCategory": "Daily",
    "festivalDay": "Daily",
    "festivalYear": "2024",
    "date": "2024-09-08",
    "startTime": "12:00",
    "endTime": "14:00",
    "venue": "Mandal Ground, Pune",
    "description": "Daily prasad distribution to all devotees.",
    "organizer": "Anjali More",
    "coordinator": "Suresh Pawar",
    "budget": 10000,
    "status": "In Progress"
  }
];

export default events;
