const volunteers = [
  {
    "id": "VOL-0001",
    "name": "Rajesh Deshmukh",
    "mobile": "9876543210",
    "email": "rajesh.deshmukh@email.com",
    "address": "Shivaji Nagar, Pune",
    "profilePhoto": null,
    "dateOfBirth": "1985-06-15",
    "gender": "Male",
    "bloodGroup": "B+",
    "emergencyContact": "9876543211",
    "aadhaarNumber": "1234-5678-9012",
    "festivalYear": "2024",
    "category": "Core Committee",
    "role": "President",
    "skills": "Leadership, Event Management",
    "experience": "10 years",
    "availability": "Full Day",
    "joiningDate": "2020-08-15",
    "status": "Active"
  },
  {
    "id": "VOL-0002",
    "name": "Priya Patil",
    "mobile": "9876543212",
    "email": "priya.patil@email.com",
    "address": "Kothrud, Pune",
    "profilePhoto": null,
    "dateOfBirth": "1990-03-22",
    "gender": "Female",
    "bloodGroup": "A+",
    "emergencyContact": "9876543213",
    "aadhaarNumber": "2345-6789-0123",
    "festivalYear": "2024",
    "category": "Core Committee",
    "role": "Secretary",
    "skills": "Communication, Planning",
    "experience": "5 years",
    "availability": "Full Day",
    "joiningDate": "2021-01-10",
    "status": "Active"
  },
  {
    "id": "VOL-0003",
    "name": "Amit Kumar",
    "mobile": "9876543214",
    "email": "amit.kumar@email.com",
    "address": "Baner, Pune",
    "profilePhoto": null,
    "dateOfBirth": "1988-11-05",
    "gender": "Male",
    "bloodGroup": "O+",
    "emergencyContact": "9876543215",
    "aadhaarNumber": "3456-7890-1234",
    "festivalYear": "2024",
    "category": "Event Management",
    "role": "Event Organizer",
    "skills": "Event Planning, Coordination",
    "experience": "7 years",
    "availability": "Full Day",
    "joiningDate": "2019-12-01",
    "status": "Active"
  },
  {
    "id": "VOL-0004",
    "name": "Sneha Joshi",
    "mobile": "9876543216",
    "email": "sneha.joshi@email.com",
    "address": "Viman Nagar, Pune",
    "profilePhoto": null,
    "dateOfBirth": "1992-07-18",
    "gender": "Female",
    "bloodGroup": "AB+",
    "emergencyContact": "9876543217",
    "aadhaarNumber": "4567-8901-2345",
    "festivalYear": "2024",
    "category": "Decoration & Murti",
    "role": "Decoration Head",
    "skills": "Decoration, Art & Craft",
    "experience": "4 years",
    "availability": "Half Day - Morning",
    "joiningDate": "2022-06-15",
    "status": "Active"
  },
  {
    "id": "VOL-0005",
    "name": "Vikram Singh",
    "mobile": "9876543218",
    "email": "vikram.singh@email.com",
    "address": "Hadapsar, Pune",
    "profilePhoto": null,
    "dateOfBirth": "1987-01-30",
    "gender": "Male",
    "bloodGroup": "A-",
    "emergencyContact": "9876543219",
    "aadhaarNumber": "5678-9012-3456",
    "festivalYear": "2024",
    "category": "Security & Safety",
    "role": "Security Head",
    "skills": "Security Management, First Aid",
    "experience": "8 years",
    "availability": "Full Day",
    "joiningDate": "2018-09-20",
    "status": "Active"
  },
  {
    "id": "VOL-0006",
    "name": "Meera Kulkarni",
    "mobile": "9876543220",
    "email": "meera.kulkarni@email.com",
    "address": "Deccan Gymkhana, Pune",
    "profilePhoto": null,
    "dateOfBirth": "1995-09-12",
    "gender": "Female",
    "bloodGroup": "B-",
    "emergencyContact": "9876543221",
    "aadhaarNumber": "6789-0123-4567",
    "festivalYear": "2024",
    "category": "Social Media & Marketing",
    "role": "Social Media Manager",
    "skills": "Social Media, Photography",
    "experience": "3 years",
    "availability": "Full Day",
    "joiningDate": "2023-03-10",
    "status": "Active"
  },
  {
    "id": "VOL-0007",
    "name": "Suresh Pawar",
    "mobile": "9876543222",
    "email": "suresh.pawar@email.com",
    "address": "Pimpri, Pune",
    "profilePhoto": null,
    "dateOfBirth": "1983-04-25",
    "gender": "Male",
    "bloodGroup": "O-",
    "emergencyContact": "9876543223",
    "aadhaarNumber": "7890-1234-5678",
    "festivalYear": "2024",
    "category": "Finance",
    "role": "Cash Collection Volunteer",
    "skills": "Accounting, Finance",
    "experience": "12 years",
    "availability": "Full Day",
    "joiningDate": "2017-11-05",
    "status": "Active"
  },
  {
    "id": "VOL-0008",
    "name": "Anjali More",
    "mobile": "9876543224",
    "email": "anjali.more@email.com",
    "address": "Sinhagad Road, Pune",
    "profilePhoto": null,
    "dateOfBirth": "1991-08-08",
    "gender": "Female",
    "bloodGroup": "A+",
    "emergencyContact": "9876543225",
    "aadhaarNumber": "8901-2345-6789",
    "festivalYear": "2024",
    "category": "Prasad & Food",
    "role": "Prasad Coordinator",
    "skills": "Cooking, Food Safety",
    "experience": "6 years",
    "availability": "Half Day - Evening",
    "joiningDate": "2020-07-22",
    "status": "Active"
  },
  {
    "id": "VOL-0009",
    "name": "Deepak Sharma",
    "mobile": "9876543226",
    "email": "deepak.sharma@email.com",
    "address": "Warje, Pune",
    "profilePhoto": null,
    "dateOfBirth": "1989-12-01",
    "gender": "Male",
    "bloodGroup": "B+",
    "emergencyContact": "9876543227",
    "aadhaarNumber": "9012-3456-7890",
    "festivalYear": "2024",
    "category": "Logistics",
    "role": "Sound System Coordinator",
    "skills": "Audio Systems, Technical Setup",
    "experience": "5 years",
    "availability": "Full Day",
    "joiningDate": "2021-04-18",
    "status": "Active"
  },
  {
    "id": "VOL-0010",
    "name": "Kavita Bhosale",
    "mobile": "9876543228",
    "email": "kavita.bhosale@email.com",
    "address": "Aundh, Pune",
    "profilePhoto": null,
    "dateOfBirth": "1993-05-14",
    "gender": "Female",
    "bloodGroup": "AB-",
    "emergencyContact": "9876543229",
    "aadhaarNumber": "0123-4567-8901",
    "festivalYear": "2024",
    "category": "Public Relations",
    "role": "VIP Guest Coordinator",
    "skills": "Public Relations, Communication",
    "experience": "4 years",
    "availability": "Full Day",
    "joiningDate": "2022-02-14",
    "status": "Active"
  }
];

export default volunteers;
